apiVersion: v1
kind: Pod
metadata:
  name: s3fs-test-nginx
  namespace: default
spec:
  containers:
   - name: s3fs-test-nginx
     image: nginx
     volumeMounts:
       - mountPath: /mnt/s3
         name: webroot
  volumes:
   - name: webroot
     persistentVolumeClaim:
       claimName: csi-s3-pvc
       readOnly: false
